name: meus_gols_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  localstorage: ^5.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  go_router: ^14.1.0
  provider: ^6.1.2
  intl: ^0.19.0
  permission_handler: ^11.3.1
  freezed: ^3.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  getwidget: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
